<languages/>
<translate>

<!--T:13-->
{{Docnav
|[[PartDesign_Sprocket|Sprocket]]
|[[PartDesign_WizardShaft|Shaft design wizard]]
|[[PartDesign_Workbench|PartDesign]]
|IconL=PartDesign_Sprocket.svg
|IconR=WizardShaft.svg
|IconC=Workbench_PartDesign.svg
}}

<!--T:1-->
{{GuiCommand
|Name=PartDesign InvoluteGear
|MenuLocation=Part Design → Involute gear...
|Workbenches=[[PartDesign_Workbench|PartDesign]]
|SeeAlso=[[FCGear_Workbench|FCGear Workbench]]
}}

== Description == <!--T:20-->

<!--T:2-->
This tool allows you to create a 2D profile of an involute gear or spline. This 2D profile is fully parametric, and can be padded with the [[PartDesign_Pad|PartDesign Pad]] or [[PartDesign_AdditiveHelix|PartDesign AdditiveHelix]] feature.

<!--T:21-->
For more detailed information see Wikipedia's entries for: [https://en.wikipedia.org/wiki/Gear Gear] and [https://en.wikipedia.org/wiki/Involute_gear Involute Gear]

</translate>
[[File:PartDesign_Involute_Gear_01.png|800px]]
<translate>

==Usage== <!--T:22-->

=== Create the profile === <!--T:25-->

<!--T:6-->
# Optionally activate the correct body.
# Select the {{MenuCommand|Part Design → [[File:PartDesign_InvoluteGear.svg|16px]] Involute gear...}} option from the menu.
# Set the Involute parameters.
# Click {{Button|OK}}.
# If there was no active body: drag and drop the gear into a body for the application of further features like padding.

=== Create a spur gear === <!--T:26-->

<!--T:27-->
# Select the gear profile in the [[Tree_view|Tree view]].
# Press the {{Button|[[Image:PartDesign_Pad.svg|16px]] [[PartDesign_Pad|PartDesign Pad]]}} button.
# Set the pad's {{PropertyData|Length}} to the desired face width of the gear.
# Click {{Button|OK}}.

=== Create a helical gear === <!--T:28-->

<!--T:30-->
# Select the gear profile in the [[Tree_view|Tree view]].
# Press the {{Button|[[Image:PartDesign_AdditiveHelix.svg|16px]] [[PartDesign_AdditiveHelix|PartDesign AdditiveHelix]]}} button.
# Choose as Axis the normal of the gear profile, that is {{MenuCommand|Normal sketch axis}} {{Version|0.20}}. (In earlier versions the {{MenuCommand|Base Z axis}} can be used as long as the profile's plane has not been altered.)
# Choose a {{MenuCommand|Height-Turns}} mode.
# Set the {{PropertyData|Height}} to the desired face width of the gear.
# To set the desired helical angle an [[Expressions|Expression]] for the {{PropertyData|Turns}} is required.
## Click the blue [[Image:Bound-expression.svg|16px]] icon at the right of the input field.
## Enter the following formula: {{incode|Height * tan(25°) / (InvoluteGear.NumberOfTeeth * InvoluteGear.Modules * pi)}}, where {{incode|25°}} is an example for the desired helical angle (also known as beta-value) and {{incode|InvoluteGear}} is the  {{PropertyData|Name}} of the profile.
## Click {{Button|OK}} to close the formula editor.
# Click {{Button|OK}} to close the task panel.

<!--T:31-->
Hint: To make the helical angle an accessible parameter, use a ''dynamic property'':
# Select the profile.
# In the [[Property_editor|Property editor]] select the {{MenuCommand|Add Property}} option in the context menu.
# In the {{MenuCommand|Add Property}} dialog:
## Choose {{incode|App::PropertyAngle}} as Type.
## Set {{incode|Gear}} as Group.
## Set {{incode|HelicalAngle}} as Name (without a space).
## Click {{Button|OK}}.
# Now a new property {{PropertyData|Helical Angle}} (space added automatically), with an initial value of {{incode|0.0°}}, becomes available.
# Assign the desired helical angle to the new property.
# In the formula of the {{PropertyData|Turns}} property of the AdditiveHelix, you can now reference {{incode|InvoluteGear.HelicalAngle}} instead of the hard coded value of e.g. {{incode|25°}}; again assuming {{incode|InvoluteGear}} is the {{PropertyData|Name}} of the profile.

=== Cut a hub for an involute splined shaft === <!--T:35-->

<!--T:36-->
{{Version|0.21}}

<!--T:37-->
# Activate the correct body.
# Create an internal involute gear profile with the required number of grooves and adapt the values of pressure angle, addendum-, dedendum- and root fillet coefficient. See also the table in [[#Notes|Notes]] below for feasible values. For example:
#* {{PropertyData|External Gear}}: False
#* {{PropertyData|Number Of Teeth}}: 12
#* {{PropertyData|Pressure Angle}}: 37.5°
#* {{PropertyData|Addendum Coefficient}}: 0.45
#* {{PropertyData|Dedendum Coefficient}}: 0.7
#* {{PropertyData|Root Fillet Coefficient}}: 0.3
# Select the gear profile in the [[Tree_view|Tree view]].
# Press the {{Button|[[Image:PartDesign_Pocket.svg|16px]] '''Pocket'''}} button.
# Set the pocket's {{PropertyData|Type}} to '''Through All'''.
# Check the pocket's {{PropertyData|Symmetric To Plane}} option.
# Click  {{Button|OK}}.

== Properties == <!--T:32-->

<!--T:38-->
* {{PropertyData|Addendum Coefficient}}: The height of the tooth from the pitch circle up to its tip, normalized by the module. Default is 1.0 for the standard full-depth system. {{Version|0.21}}

<!--T:39-->
* {{PropertyData|Dedendum Coefficient}}: The height of the tooth from the pitch circle down to its root, normalized by the module. Default is 1.25 for the standard full-depth system. {{Version|0.21}}

<!--T:11-->
* {{PropertyData|External Gear}}: True or false.

<!--T:10-->
* {{PropertyData|High Precision}}: True or false.

<!--T:8-->
* {{PropertyData|Modules}}: Pitch diameter divided by the number of teeth. (Note: the correct technical term is "Module", but this name is already used by FreeCAD's internals and thus cannot be used here.)

<!--T:7-->
* {{PropertyData|Number Of Teeth}}: Sets the number of teeth.

<!--T:9-->
* {{PropertyData|Pressure Angle}}: Acute angle between the line of action and a normal to the line connecting the gear centers. Default is 20 °. See [https://en.wikipedia.org/wiki/Involute_gear Involute gear].

<!--T:48-->
* {{PropertyData|Profile Shift Coefficient}}: The distance by which the reference profile is shifted outwards, normalized by the module. Default is zero. Profile shift may be positive or negative. {{Version|0.21}}

<!--T:40-->
* {{PropertyData|Root Fillet Coefficient}}: The radius of the fillet at the root of the tooth, normalized by the module. Default is 0.38 as defined by the ISO rack. {{Version|0.21}}

== Notes == <!--T:41-->

<!--T:42-->
* In order for two gears to mesh they need to share the same module and pressure angle. [[Expressions|Expressions]] may help to ensure consistency. Their center distance needs to be {{incode|(NumberOfTeeth + OtherGear.NumberOfTeeth) * Modules / 2}} (that is in case of the sum profile shift being zero). Subtract the number of teeth in case of an internal gear.

<!--T:50-->
* When using a [[Sketch|Sketch]] to position some gears, they can be represented using their pitch circles and using a [[Sketcher_ConstrainTangent|tangent constraint]] between those circles. Their diameters can be set by the following [[Expressions|Expression]]: {{incode|SomeGear.NumberOfTeeth * SomeGear.Modules}} (assuming no profile shift and "SomeGear" being the {{PropertyData|Name}} of the respective gear profile object).

<!--T:51-->
* When using [[Sketch|Sketches]] to create additional features (cutouts, spokes, ...) on a gear, reference circles at the tip or the root of the teeth can help positioning those features. The diameter of the tip circle can be set by the following [[Expressions|Expression]]: {{incode|(SomeGear.NumberOfTeeth + 2 * (SomeGear.AddendumCoefficient + SomeGear.ProfileShiftCoefficient)) * SomeGear.Modules}} and the root circle respectively by {{incode|(SomeGear.NumberOfTeeth - 2 * (SomeGear.DedendumCoefficient - SomeGear.ProfileShiftCoefficient)) * SomeGear.Modules}}.

<!--T:49-->
* Profile shifting can be used to prevent undercut on gears with a small number of teeth. Another application is to adjust the center distance of two gears with a given number of teeth and module.

<!--T:43-->
* When visually checking for proper meshing or interferences a much lower value for {{PropertyView|Deviation}} is helpful, e.g. 0.05 instead of the default 0.5. Otherwise the representation in the [[3D_view|3D view]] may be too coarse.

<!--T:44-->
* For standard gears the most common pressure angle is 20 °, followed by 14,5 °. Other applications, notably [https://en.wikipedia.org/wiki/Spline_(mechanical) splines], use higher angles.

<!--T:45-->
* The standard full-depth system uses an addendum coefficient of 1.0 and a dedendum coefficient of 1.25, resulting in a clearance of 0.25 (the difference between the addendum of the one gear and the dedendum of the other). The actual tooth length is the sum of both coefficients, multiplied by the module.

<!--T:46-->
* Tooth length reduction may be required to prevent undercut or to strengthen the teeth (see [https://khkgears.net/new/gear_knowledge/gear-nomenclature/stub-teeth.html stub teeth]). For internal gears the addendum (here pointing inwards) may need shortening to avoid certain interferences or non-involute flanks; when indicated in combination with longer teeth of the pinion.

<!--T:47-->
* For splined shafts and hubs ISO 4156 defines the following parameters:
: {| class="wikitable"
|-
! Pressure Angle          !! 30 ° (flat root) !! 30 ° (fillet root) !! 37,5 ° !! 45 °
|-
| Addendum Coefficient    || 0.5 || 0.5 || 0.45 || 0.4
|-
| Dedendum Coefficient    || 0.75 || 0.9 || 0.7 || 0.6
|-
| Root Fillet Coefficient || 0.2 || 0.4 || 0.3 || 0.25
|}

==Limitations== <!--T:33-->

<!--T:52-->
* It is currently not possible to adjust the tooth thickness. Tooth and tooth space are distributed equally on the reference circle. One way to still control backlash is to adjust the center distance in a gear paring. Another is to apply a tiny amount of negative profile shift. Example: For a typical circumferential backlash coefficient of 0.04 increase either the center distance by {{incode|(0.04 * Modules / 2) / tan(PressureAngle)}} or shift the profile of one gear (preferably the larger one) by a coefficient of {{incode|-(0.04 / 2) / tan(PressureAngle))}}.

<!--T:34-->
* There is currently no [https://www.tec-science.com/mechanical-power-transmission/involute-gear/undercut/ undercut] in the generated gear profile. That means gears with a low number of teeth can interfere with the teeth of the mating gear. The lower limit depends on the {{PropertyData|Pressure Angle}} and is around 17 teeth for 20° and 32 for 14.5°. Most practical applications tolerate a missing undercut for gears a little smaller than this theoretical limit though, which assumes mating with a rack and standard tooth length.

==Tutorials== <!--T:23-->

<!--T:24-->
Video: [https://www.youtube.com/watch?v=8VNhTrnFMfE How to make gears in FreeCAD]

==Related== <!--T:18-->

<!--T:19-->
* [[FCGear_Workbench|FCGear Workbench]]


<!--T:14-->
{{Docnav
|[[PartDesign_Sprocket|Sprocket]]
|[[PartDesign_WizardShaft|Shaft design wizard]]
|[[PartDesign_Workbench|PartDesign]]
|IconL=PartDesign_Sprocket.svg
|IconR=WizardShaft.svg
|IconC=Workbench_PartDesign.svg
}}

</translate>
{{PartDesign Tools navi{{#translation:}}}}
{{Userdocnavi{{#translation:}}}}